[package]
authors = ["Nipuna Fernando"]
distribution = "2201.0.0"
icon = "icon.png"
keywords = ["Toml", "Parser"]
license = ["Apache-2.0"]
name = "toml"
org = "nipunayf"
repository = "https://github.com/nipunayf/ballerina-toml"
version = "0.1.0"

[build-options]
observabilityIncluded = true
