[package]
license=["Apache-2.0"]
keywords=["Toml", "Parser"]
org="nipunayf"
name="toml"
icon = "icon.png"
distribution = "2201.0.0"
repository="https://github.com/nipunayf/module-ballerina-toml"
authors=["Nipuna Fernando"]

[build-options]
observabilityIncluded = true
